#!/bin/bash
USERNAME='ubuntu'
runuser -l $USERNAME -c 'git clone https://github.com/touho/openeditplay /home/${USERNAME}/openeditplay'
runuser -l $USERNAME -c '/home/${USERNAME}/openeditplay/installation/amazon/installAmazonEC2Ubuntu'
