#!/bin/bash
# This script is run by root user. Environment varibles can not be used.

runuser -l ubuntu -c 'git clone https://github.com/touho/openeditplay /home/ubuntu/openeditplay'
runuser -l ubuntu -c '/home/ubuntu/openeditplay/installation/amazon/installAmazonEC2Ubuntu'
