#!/bin/bash

# set working directory to script directory
cd "$(dirname "$0")"

# to root directory
cd ../..

echo "Installing nvm"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash >/dev/null;
. ~/.nvm/nvm.sh

echo "Installing Node.js"
nvm install 8 >/dev/null

echo "Installing Open Edit Play"
npm install --production >/dev/null
cp installation/amazon/configAmazon.js config.js

echo "Updating apt-get"
sudo apt-get update >/dev/null
# DEBIAN_FRONTEND=noninteractive sudo apt-get -y upgrade # This takes very long and is human-interactive

echo "Installing nginx"
yes Y | sudo apt-get install nginx >/dev/null

echo "Setupping nginx"
sudo cp installation/nginxConfig /etc/nginx/sites-available/openeditplay >/dev/null
sudo ln -s /etc/nginx/sites-available/openeditplay /etc/nginx/sites-enabled/openeditplay >/dev/null
sudo rm /etc/nginx/sites-enabled/default >/dev/null
sudo service nginx restart >/dev/null

echo "Installing pm2"
npm i -g pm2 >/dev/null
#sudo pm2 startup # doesn't work with sudo. would require 

# Create easy update script
echo "cd ~/openeditplay;git pull;npm install;pm2 restart server;echo 'Open Edit Play has been updated!'" > ~/updateFromGit
chmod +x ~/updateFromGit

# MySQL password
PASSWORD=`openssl rand -base64 32`
echo $PASSWORD > ~/.pw

# Install MySQL Server in a Non-Interactive mode.
echo "Installing MySQL database"
installation/amazon/mySQLNonInteractiveInstall $PASSWORD

# sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/data-dir select ''"
# sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/root-pass password $PASSWORD"
# sudo debconf-set-selections <<< "mysql-community-server mysql-community-server/re-root-pass password $PASSWORD"
# sudo apt-get install -y mysql-server

sudo mysql --password="${PASSWORD}" -e "
    CREATE DATABASE openeditplay CHARACTER SET utf8;
    CREATE USER 'openeditplay'@'localhost' IDENTIFIED BY '${PASSWORD}';
    GRANT ALL ON openeditplay.* TO 'openeditplay'@'localhost';
"
mysql -u openeditplay --password="${PASSWORD}" --database=openeditplay < installation/resetDatabase.sql

echo "Starting Open Edit Play server"
pm2 start server.js --name openeditplay >/dev/null
pm2 save >/dev/null

pm2 startup | grep sudo | bash >/dev/null

echo ""
echo "[ Open Edit Play ]"
echo ""
echo "Server is up and running. It will also start on reboot."
