#!/bin/bash

# set working directory to script directory
cd "$(dirname "$0")"

# to root directory
cd ..

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash;
. ~/.nvm/nvm.sh

nvm install 8

node -e "console.log('Running Node.js ' + process.version)"

mkdir gameData

npm install --production


sudo apt-get update
yes Y | sudo apt-get install nginx

sudo cp ./nginxConfig /etc/nginx/sites-available/openeditplay
sudo ln -s /etc/nginx/sites-available/openeditplay /etc/nginx/sites-enabled/openeditplay
sudo service nginx restart

npm i -g pm2

pm2 startup
pm2 start server.js
pm2 save

echo "Open Edit Play server installed. To run it type 'node server.js'"
