#!/bin/bash

# set working directory to script directory
cd "$(dirname "$0")"

# to root directory
cd ..

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash;
. ~/.nvm/nvm.sh

nvm install 8

node -e "console.log('Running Node.js ' + process.version)"

mkdir gameData

npm install --production

echo "Open Edit Play server installed. To run it type 'node server.js'"
